DROP SEQUENCE SEQ_RESTAURANT;
DROP SEQUENCE SEQ_CLIENT;
DROP SEQUENCE SEQ_COMMANDE;
DROP SEQUENCE SEQ_PRODUIT;

DROP TABLE PRODUIT_COMMANDE CASCADE CONSTRAINTS;
DROP TABLE COMMANDE CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE PRODUIT CASCADE CONSTRAINTS;
DROP TABLE RESTAURANT CASCADE CONSTRAINTS;

DROP TRIGGER TR_BI_RESTAURANT;

DROP TRIGGER TR_BI_CLIENT;

DROP TRIGGER TR_BI_COMMANDE;

DROP TRIGGER TR_BI_PRODUIT;
